---
preprocess_financial_data:
  description:
    Load financial transaction data from {financial_data_path} using CSVSearchTool.
    Perform initial cleaning to remove inconsistencies and format the data properly.
    Store the cleaned dataset as {clean_transactions_data}.
  expected_output: A cleaned dataset of financial transactions stored as {clean_transactions_data}.
  async_execution: false
  agent: data_ingestor
organize_transactions_data:
  description:
    Structure the cleaned financial data {clean_transactions_data} into
    a well-organized format suitable for anomaly detection algorithms.
  expected_output:
    Structured financial transaction data ready for anomaly detection,
    referenced as {clean_transactions_data}.
  async_execution: false
  agent: data_ingestor
  context:
    - preprocess_financial_data
analyze_data_for_anomalies:
  description:
    Apply anomaly detection algorithms to the structured data {clean_transactions_data}
    to identify deviations from expected patterns. Flag potential anomalies and store
    them as {anomaly_list}.
  expected_output: A preliminary list of potential anomalies stored as {anomaly_list}.
  async_execution: false
  agent: anomaly_detector
  context:
    - organize_transactions_data
validate_anomalies_against_criteria:
  description:
    Filter the preliminary {anomaly_list} by verifying each anomaly against
    business rules and thresholds defined in {reconciliation_rules}. Refine the anomaly
    list by removing false positives.
  expected_output: A refined and validated list of anomalies stored as {anomaly_list}.
  async_execution: false
  agent: anomaly_detector
  context:
    - analyze_data_for_anomalies
cross_check_anomalies_with_records:
  description:
    For each anomaly in {anomaly_list}, cross-check detailed transaction
    information against historical data from {financial_data_path} and apply {reconciliation_rules}.
    Produce a detailed {reconciliation_report} with recommendations for adjustments.
  expected_output:
    A detailed reconciliation report stored as {reconciliation_report}
    identifying mismatches and corrective actions.
  async_execution: false
  agent: reconciliation_expert
  context:
    - validate_anomalies_against_criteria
generate_comprehensive_report:
  description:
    Combine the {clean_transactions_data}, the refined {anomaly_list},
    and the {reconciliation_report} into a final report. This report {final_report}
    should provide clear insights and recommendations for further financial decision-making.
  expected_output:
    A final comprehensive report stored as {final_report} summarizing
    the anomaly detection and reconciliation process.
  async_execution: false
  agent: report_generator
  context:
    - cross_check_anomalies_with_records
